# SPDX-FileCopyrightText: © 2026 Jeffrey C. Ollie
# SPDX-License-Identifier: MIT

name: test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: nixos
    env:
      ZIG_LOCAL_CACHE_DIR: /zig/local-cache
      ZIG_GLOBAL_CACHE_DIR: /zig/global-cache
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Check formatting
        run: nix develop .#default -c zig fmt --check .

      - name: Check REUSE compliance
        run: nix develop .#default -c reuse lint

      - name: Run tests
        run: nix develop .#default -c zig build test

      - name: Build API docs
        run: nix develop .#default -c zig build docs
